/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for monitoring services.
         *     Returns current status and timestamp.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Simple ping endpoint to verify API is responding.
         *     Returns immediately with pong response.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout endpoint that destroys the user's session.
         *
         *     Uses SessionService for session destruction (business logic) and
         *     session cookie functions for cookie clearing (HTTP concern).
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/telegram/code/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Verification Code
         * @description Send 6-digit verification code to user's Telegram DM.
         */
        post: operations["send_verification_code_auth_login_telegram_code_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/telegram/code/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Code And Login
         * @description Verify 6-digit code and create authenticated session.
         *
         *     Uses SessionService for session creation (business logic) and
         *     session cookie functions for cookie setting (HTTP concern).
         */
        post: operations["verify_code_and_login_auth_login_telegram_code_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/telegram/deeplink/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Deeplink Login
         * @description Start Telegram deep link login flow.
         *
         *     Returns a token and bot URL. User should be redirected to bot URL.
         *     Frontend should then poll /poll endpoint.
         */
        post: operations["start_deeplink_login_auth_login_telegram_deeplink_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/telegram/deeplink/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Deeplink Login
         * @description Check status of deep link login token.
         *
         *     Frontend should poll this endpoint after redirecting user to Telegram.
         *     When status is "verified", session cookie is set and user is logged in.
         */
        get: operations["poll_deeplink_login_auth_login_telegram_deeplink_poll_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/email/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Signup
         * @description Start email signup flow.
         *
         *     Sends verification code to provided email address.
         *     Returns signup token for subsequent requests.
         */
        post: operations["start_signup_auth_signup_email_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/email/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Signup
         * @description Complete email signup.
         *
         *     Verifies code, validates password, creates user account.
         *     Sets session cookie on success.
         */
        post: operations["complete_signup_auth_signup_email_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with email or username and password.
         *
         *     Sets session cookie on success.
         */
        post: operations["login_auth_login_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/email/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Link
         * @description Start email linking flow for authenticated Telegram users.
         *
         *     Sends verification code to provided email address.
         */
        post: operations["start_link_auth_link_email_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/email/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Link
         * @description Complete email linking flow.
         *
         *     Verifies code and sets password for email login.
         */
        post: operations["complete_link_auth_link_email_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Reset
         * @description Start password reset flow.
         *
         *     Sends verification code to provided email address.
         *     Returns reset token for subsequent requests.
         */
        post: operations["start_reset_auth_password_reset_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Reset
         * @description Complete password reset.
         *
         *     Verifies code and sets new password.
         */
        post: operations["complete_reset_auth_password_reset_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Code
         * @description Resend verification code.
         *
         *     For signup flow: provide signup_token.
         *     For link flow: requires authentication (uses current user_id).
         */
        post: operations["resend_code_auth_signup_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/telegram/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Link
         * @description Start Telegram account linking flow.
         *
         *     Generates a link token and returns bot URL with deep link.
         *     User should open the bot URL to complete linking.
         */
        post: operations["start_link_auth_link_telegram_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/telegram/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Link Status
         * @description Poll link token status.
         *
         *     Frontend polls this endpoint to detect when linking completes.
         *     Returns status: "pending" | "completed" | "expired"
         */
        get: operations["poll_link_status_auth_link_telegram_poll_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Products
         * @description Get available products for purchase.
         *
         *     Returns products excluding test products, suitable for profile/shop pages.
         */
        get: operations["get_products_payments_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/start_purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Purchase
         * @description Start a payment for a product.
         *
         *     Creates a payment and returns a confirmation URL for the user to complete payment.
         *     Supports multiple payment providers (YooKassa, Telegram Stars, etc).
         */
        post: operations["start_purchase_payments_start_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscription
         * @description Get current subscription with details for authenticated user.
         */
        get: operations["get_subscription_subscriptions__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Subscription
         * @description Cancel current subscription with optional reason and feedback.
         */
        post: operations["cancel_subscription_subscriptions_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current authenticated user profile.
         */
        get: operations["get_current_user_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Current User
         * @description Update current authenticated user profile.
         */
        patch: operations["update_current_user_users_me_patch"];
        trace?: never;
    };
    "/yookassa/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yookassa Webhook
         * @description Webhook endpoint for YooKassa payment confirmations.
         *
         *     Returns:
         *         - 200 OK: Webhook processed successfully
         *         - 400 Bad Request: Invalid JSON, missing fields, permanent business errors
         *         - 500 Internal Error: Transient business errors, unknown errors
         *         - 503 Service Unavailable: Infrastructure errors (DB, Redis)
         */
        post: operations["yookassa_webhook_yookassa_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram-stars/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Stars Webhook
         * @description Webhook endpoint for Telegram Stars payment confirmations from web interface.
         *
         *     This endpoint receives payment notifications from Telegram when payments
         *     are made through the web interface and processes them through the unified
         *     payment system.
         *
         *     Returns:
         *         - 200 OK: Webhook processed successfully
         *         - 400 Bad Request: Invalid JSON, missing fields, permanent business errors
         *         - 500 Internal Error: Transient business errors, unknown errors
         *         - 503 Service Unavailable: Infrastructure errors (DB, Redis)
         */
        post: operations["telegram_stars_webhook_telegram_stars_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Friends */
        get: operations["get_friends_friends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/add_friend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Friend */
        post: operations["add_friend_add_friend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Create Invite */
        get: operations["create_invite_create_invite_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process_start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Start */
        post: operations["process_start_process_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Permissions */
        get: operations["get_my_permissions_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/demo-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Protected Action */
        post: operations["demo_protected_action_admin_demo_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/slow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slow Endpoint
         * @description Endpoint with artificial delay for loading state demo.
         *
         *     Args:
         *         delay_ms: Delay in milliseconds (100-10000, default 2000)
         */
        get: operations["slow_endpoint_demo_slow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/unreliable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unreliable Endpoint
         * @description Endpoint that randomly fails for error handling demo.
         *
         *     Args:
         *         fail_rate: Probability of failure (0-1, default 0.5)
         */
        get: operations["unreliable_endpoint_demo_unreliable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/counter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Counter
         * @description Get current counter value for cache demo.
         *
         *     Args:
         *         counter_id: Unique counter ID (default: "default"). Use different IDs
         *                    to avoid conflicts between users/sessions.
         */
        get: operations["get_counter_demo_counter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/counter/increment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Increment Counter
         * @description Increment counter for optimistic update demo.
         *
         *     Args:
         *         counter_id: Unique counter ID (default: "default")
         *         amount: Amount to increment (1-100, default 1)
         *         should_fail: If true, fails after delay (for rollback demo)
         */
        post: operations["increment_counter_demo_counter_increment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/counter/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Counter
         * @description Reset counter to 0.
         *
         *     Args:
         *         counter_id: Unique counter ID (default: "default")
         */
        post: operations["reset_counter_demo_counter_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule Notification
         * @description Schedule a delayed Telegram notification for demo.
         *
         *     Requires Telegram authentication (guest users not supported).
         *
         *     Args:
         *         delay_seconds: Delay before sending (1-60 seconds)
         */
        post: operations["schedule_notification_demo_notify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paginated Items
         * @description Paginated items endpoint for infinite scroll demo.
         *
         *     Args:
         *         cursor: Starting index (default 0)
         *         limit: Items per page (1-50, default 10)
         *         delay_ms: Artificial delay in milliseconds (0-3000, default 500)
         */
        get: operations["get_paginated_items_demo_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item Detail
         * @description Item detail endpoint for prefetch demo.
         *
         *     Args:
         *         item_id: Item ID (1-100)
         *         delay_ms: Artificial delay in milliseconds (0-3000, default 300)
         */
        get: operations["get_item_detail_demo_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Time
         * @description Server time endpoint for polling demo.
         *     Returns current server timestamp.
         */
        get: operations["get_server_time_demo_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weather
         * @description Mock weather data for parallel queries demo.
         */
        get: operations["get_weather_demo_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock
         * @description Mock stock data for parallel queries demo.
         */
        get: operations["get_stock_demo_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get News
         * @description Mock news data for parallel queries demo.
         */
        get: operations["get_news_demo_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/error/{status_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trigger Error
         * @description Trigger specific HTTP error for error handling demo.
         *
         *     Args:
         *         status_code: HTTP status code to return (400-599)
         *         delay_ms: Optional delay before returning error
         */
        get: operations["trigger_error_demo_error__status_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/rbac/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rbac Me
         * @description Get your current role and permissions for RBAC demo.
         */
        get: operations["get_rbac_me_demo_rbac_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/rbac/set-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Demo Role
         * @description Change your role for demo purposes (debug mode only).
         *
         *     This allows testing different permission levels without
         *     needing actual admin access.
         */
        post: operations["set_demo_role_demo_rbac_set_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/rbac/protected-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Protected Action
         * @description Demo endpoint that requires owner role.
         *
         *     Use this to test permission checks - only owners can execute this action.
         */
        post: operations["demo_protected_action_demo_rbac_protected_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatsResponse */
        AdminStatsResponse: {
            /** Total Users */
            total_users: number;
            /** Users By Role */
            users_by_role: {
                [key: string]: number;
            };
        };
        /** CancelSubscriptionRequest */
        CancelSubscriptionRequest: {
            /**
             * Reason
             * @description Cancellation reason code
             */
            reason?: string | null;
            /**
             * Feedback
             * @description Optional user feedback
             */
            feedback?: string | null;
        };
        /** CounterResponse */
        CounterResponse: {
            /** Value */
            value: number;
            /** Counter Id */
            counter_id: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * DeeplinkLoginPollResponse
         * @description Response for checking deep link login status.
         */
        DeeplinkLoginPollResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "verified" | "expired";
            /** User Id */
            user_id?: string | null;
        };
        /**
         * DeeplinkLoginStartResponse
         * @description Response for starting deep link login.
         */
        DeeplinkLoginStartResponse: {
            /** Token */
            token: string;
            /** Bot Url */
            bot_url: string;
            /**
             * Expires In
             * @default 300
             */
            expires_in: number;
        };
        /** DemoActionResponse */
        DemoActionResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Required Role */
            required_role: string;
        };
        /**
         * EmailLinkCompleteRequest
         * @description Request to complete email linking.
         */
        EmailLinkCompleteRequest: {
            /** Code */
            code: string;
            /** Password */
            password: string;
        };
        /**
         * EmailLinkCompleteResponse
         * @description Response for successful email linking.
         */
        EmailLinkCompleteResponse: {
            /**
             * Message
             * @default Email linked successfully
             */
            message: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /**
         * EmailLinkRequest
         * @description Request to start email linking for Telegram users.
         */
        EmailLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * EmailLinkResponse
         * @description Response for starting email link flow.
         */
        EmailLinkResponse: {
            /**
             * Message
             * @default Verification code sent
             */
            message: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * EmailLoginRequest
         * @description Request to login with email or username.
         */
        EmailLoginRequest: {
            /** Email Or Username */
            email_or_username: string;
            /** Password */
            password: string;
        };
        /**
         * EmailLoginResponse
         * @description Response for successful login.
         */
        EmailLoginResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string | null;
            /** Email */
            email: string;
            /**
             * Message
             * @default Login successful
             */
            message: string;
        };
        /**
         * EmailResendRequest
         * @description Request to resend verification code.
         */
        EmailResendRequest: {
            /** Signup Token */
            signup_token?: string | null;
        };
        /**
         * EmailResendResponse
         * @description Response for code resend.
         */
        EmailResendResponse: {
            /**
             * Message
             * @default Verification code sent
             */
            message: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * EmailSignupCompleteRequest
         * @description Request to complete email signup.
         */
        EmailSignupCompleteRequest: {
            /** Signup Token */
            signup_token: string;
            /** Code */
            code: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
            /** Language Code */
            language_code?: string | null;
        };
        /**
         * EmailSignupCompleteResponse
         * @description Response for successful signup completion.
         */
        EmailSignupCompleteResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /**
             * Message
             * @default Account created successfully
             */
            message: string;
        };
        /**
         * EmailSignupRequest
         * @description Request to start email signup flow.
         */
        EmailSignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * EmailSignupResponse
         * @description Response for signup initiation.
         */
        EmailSignupResponse: {
            /** Message */
            message: string;
            /** Signup Token */
            signup_token: string;
            /**
             * Expires In
             * @default 600
             */
            expires_in: number;
        };
        /**
         * ErrorResponse
         * @description Standard error response.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Message */
            message: string;
        };
        /** GroupSchema */
        GroupSchema: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /**
             * Users
             * @default []
             */
            users: components["schemas"]["UserSchema"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemDetailResponse */
        ItemDetailResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Details */
            details: string;
            /** Fetched At */
            fetched_at: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /** Message */
            message: string;
        };
        /** MyPermissionsResponse */
        MyPermissionsResponse: {
            /** Role */
            role: string;
            /** Is Owner In Config */
            is_owner_in_config: boolean;
            /** Permissions */
            permissions: string[];
        };
        /** NewsResponse */
        NewsResponse: {
            /** Headline */
            headline: string;
            /** Source */
            source: string;
            /** Fetched At */
            fetched_at: string;
        };
        /** NotifyRequest */
        NotifyRequest: {
            /**
             * Delay Seconds
             * @default 5
             */
            delay_seconds: number;
        };
        /** NotifyResponse */
        NotifyResponse: {
            /** Message */
            message: string;
            /** Delay Seconds */
            delay_seconds: number;
            /** Scheduled At */
            scheduled_at: string;
        };
        /** PaginatedItem */
        PaginatedItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** PaginatedResponse */
        PaginatedResponse: {
            /** Items */
            items: components["schemas"]["PaginatedItem"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Has More */
            has_more: boolean;
            /** Total */
            total: number;
        };
        /** PasswordResetCompleteRequest */
        PasswordResetCompleteRequest: {
            /** Reset Token */
            reset_token: string;
            /** Code */
            code: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetCompleteResponse */
        PasswordResetCompleteResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** PasswordResetStartRequest */
        PasswordResetStartRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PasswordResetStartResponse */
        PasswordResetStartResponse: {
            /** Reset Token */
            reset_token: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * PaymentProvider
         * @enum {string}
         */
        PaymentProvider: "YOOKASSA" | "TELEGRAM_STARS" | "GIFT";
        /** ProductSchema */
        ProductSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            /** Duration Days */
            duration_days: number;
            /** Is Recurring */
            is_recurring: boolean;
        };
        /**
         * ProtectedActionResponse
         * @description Response from protected action.
         */
        ProtectedActionResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Your Role */
            your_role: string;
        };
        /**
         * RbacMeResponse
         * @description Your current role and permissions.
         */
        RbacMeResponse: {
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
        };
        /** SendCodeRequest */
        SendCodeRequest: {
            /** Username */
            username: string;
        };
        /** SendCodeResponse */
        SendCodeResponse: {
            /** Message */
            message: string;
            /** Expires In */
            expires_in: number;
        };
        /** ServerTimeResponse */
        ServerTimeResponse: {
            /** Timestamp */
            timestamp: string;
            /** Unix Ms */
            unix_ms: number;
            /** Formatted */
            formatted: string;
        };
        /**
         * SetRoleRequest
         * @description Request to change your role (demo only).
         */
        SetRoleRequest: {
            /** Role */
            role: string;
        };
        /**
         * SetRoleResponse
         * @description Response after changing role.
         */
        SetRoleResponse: {
            /** Success */
            success: boolean;
            /** Old Role */
            old_role: string;
            /** New Role */
            new_role: string;
            /** Message */
            message: string;
        };
        /** SlowResponse */
        SlowResponse: {
            /** Message */
            message: string;
            /** Timestamp */
            timestamp: string;
            /** Delay Ms */
            delay_ms: number;
        };
        /** StartData */
        StartData: {
            current_user: components["schemas"]["UserSchema"];
            inviter?: components["schemas"]["GroupSchema"] | null;
            mode?: components["schemas"]["StartMode"] | null;
        };
        /**
         * StartMode
         * @enum {string}
         */
        StartMode: "draw";
        /** StartParamsRequest */
        StartParamsRequest: {
            /** Invite Code */
            invite_code?: string | null;
            /** Referal Id */
            referal_id?: string | null;
            mode?: components["schemas"]["StartMode"] | null;
            /** Page */
            page?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** StartPurchaseRequest */
        StartPurchaseRequest: {
            /** Product Id */
            product_id: string;
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /**
             * Provider Id
             * @default YOOKASSA
             */
            provider_id: string;
            /** Return Url */
            return_url: string;
        };
        /** StartPurchaseResponse */
        StartPurchaseResponse: {
            /** Payment Id */
            payment_id: string;
            /** Confirmation Url */
            confirmation_url: string;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
        };
        /** StockResponse */
        StockResponse: {
            /** Symbol */
            symbol: string;
            /** Price */
            price: number;
            /** Change */
            change: number;
            /** Fetched At */
            fetched_at: string;
        };
        /** SubscriptionSchema */
        SubscriptionSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Product Id */
            product_id: string;
            status: components["schemas"]["SubscriptionStatus"];
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** Canceled At */
            canceled_at?: string | null;
            /** Cancellation Reason */
            cancellation_reason?: string | null;
            /** Cancellation Feedback */
            cancellation_feedback?: string | null;
            /**
             * Has Access
             * @description Determines if the subscription gives premium access.
             */
            readonly has_access: boolean;
        };
        /**
         * SubscriptionStatus
         * @enum {string}
         */
        SubscriptionStatus: "NONE" | "PENDING" | "ACTIVE" | "CANCELED" | "EXPIRED";
        /** SubscriptionWithDetailsSchema */
        SubscriptionWithDetailsSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Product Id */
            product_id: string;
            status: components["schemas"]["SubscriptionStatus"];
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** Canceled At */
            canceled_at?: string | null;
            /** Cancellation Reason */
            cancellation_reason?: string | null;
            /** Cancellation Feedback */
            cancellation_feedback?: string | null;
            provider_id: components["schemas"]["PaymentProvider"];
            /** Product Price */
            product_price: number;
            /** Currency */
            currency: string;
            /**
             * Has Access
             * @description Determines if the subscription gives premium access.
             */
            readonly has_access: boolean;
        };
        /**
         * TelegramLinkStartResponse
         * @description Response for starting Telegram link flow.
         */
        TelegramLinkStartResponse: {
            /** Link Token */
            link_token: string;
            /** Bot Url */
            bot_url: string;
            /**
             * Expires In
             * @default 300
             */
            expires_in: number;
        };
        /**
         * TelegramLinkStatusResponse
         * @description Response for checking Telegram link status.
         */
        TelegramLinkStatusResponse: {
            /** Status */
            status: string;
            /** Telegram Id */
            telegram_id?: number | null;
            /** Telegram Username */
            telegram_username?: string | null;
            /** Error */
            error?: string | null;
        };
        /** UnreliableResponse */
        UnreliableResponse: {
            /** Message */
            message: string;
            /** Timestamp */
            timestamp: string;
            /** Attempt Succeeded */
            attempt_succeeded: boolean;
        };
        /**
         * UpdateUserRequest
         * @description Request schema for updating user profile fields
         */
        UpdateUserRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Username */
            username?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Language Code */
            language_code?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Male */
            male?: boolean | null;
            /** Is Onboarded */
            is_onboarded?: boolean | null;
            /** Is Terms Accepted */
            is_terms_accepted?: boolean | null;
        };
        /**
         * UserSchema
         * @description User schema for API responses - NEVER expose password_hash
         */
        UserSchema: {
            /** Id */
            id?: string | null;
            /** @default REGISTERED */
            user_type: components["schemas"]["UserType"];
            /**
             * Role
             * @default user
             */
            role: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Username */
            username?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Language Code */
            language_code?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Male */
            male?: boolean | null;
            /** Telegram Id */
            telegram_id?: number | null;
            /** Tg First Name */
            tg_first_name?: string | null;
            /** Tg Last Name */
            tg_last_name?: string | null;
            /** Tg Username */
            tg_username?: string | null;
            /** Tg Language Code */
            tg_language_code?: string | null;
            /** Tg Is Premium */
            tg_is_premium?: boolean | null;
            /** Tg Photo Url */
            tg_photo_url?: string | null;
            /** Tg Is Bot */
            tg_is_bot?: boolean | null;
            /** Tg Added To Attachment Menu */
            tg_added_to_attachment_menu?: boolean | null;
            /** Tg Allows Write To Pm */
            tg_allows_write_to_pm?: boolean | null;
            /** Email */
            email?: string | null;
            /**
             * Email Verified
             * @default false
             */
            email_verified: boolean;
            /** Email Verified At */
            email_verified_at?: string | null;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Current Streak
             * @default 0
             */
            current_streak: number;
            /**
             * Best Streak
             * @default 0
             */
            best_streak: number;
            /**
             * Total Active Days
             * @default 0
             */
            total_active_days: number;
            /** Last Activity Date */
            last_activity_date?: string | null;
            /** Is Onboarded */
            is_onboarded?: boolean | null;
            /** Is Terms Accepted */
            is_terms_accepted?: boolean | null;
            /** Referral Code */
            referral_code?: string | null;
        };
        /**
         * UserType
         * @enum {string}
         */
        UserType: "GUEST" | "REGISTERED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyCodeRequest */
        VerifyCodeRequest: {
            /** Username */
            username: string;
            /** Code */
            code: string;
        };
        /** VerifyCodeResponse */
        VerifyCodeResponse: {
            user: components["schemas"]["UserSchema"];
            /** Message */
            message: string;
        };
        /** WeatherResponse */
        WeatherResponse: {
            /** City */
            city: string;
            /** Temperature */
            temperature: number;
            /** Condition */
            condition: string;
            /** Fetched At */
            fetched_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    send_verification_code_auth_login_telegram_code_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_code_and_login_auth_login_telegram_code_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_deeplink_login_auth_login_telegram_deeplink_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeeplinkLoginStartResponse"];
                };
            };
        };
    };
    poll_deeplink_login_auth_login_telegram_deeplink_poll_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeeplinkLoginPollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_signup_auth_signup_email_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSignupResponse"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_signup_auth_signup_email_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailSignupCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSignupCompleteResponse"];
                };
            };
            /** @description Invalid code or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailLoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Account locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_link_auth_link_email_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailLinkResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_link_auth_link_email_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailLinkCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailLinkCompleteResponse"];
                };
            };
            /** @description Invalid code or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Code expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_reset_auth_password_reset_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetStartResponse"];
                };
            };
            /** @description Email not found */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_reset_auth_password_reset_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetCompleteResponse"];
                };
            };
            /** @description Invalid code or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_code_auth_signup_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailResendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailResendResponse"];
                };
            };
            /** @description Invalid token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_link_auth_link_telegram_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkStartResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Already linked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    poll_link_status_auth_link_telegram_poll_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkStatusResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_payments_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSchema"][];
                };
            };
        };
    };
    start_purchase_payments_start_purchase_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartPurchaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartPurchaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_subscriptions__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionWithDetailsSchema"];
                };
            };
        };
    };
    cancel_subscription_subscriptions_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
        };
    };
    update_current_user_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yookassa_webhook_yookassa_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    telegram_stars_webhook_telegram_stars_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_friends_friends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"][];
                };
            };
        };
    };
    add_friend_add_friend_post: {
        parameters: {
            query: {
                friend_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_create_invite_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    process_start_process_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartParamsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
        };
    };
    get_my_permissions_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPermissionsResponse"];
                };
            };
        };
    };
    demo_protected_action_admin_demo_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoActionResponse"];
                };
            };
        };
    };
    slow_endpoint_demo_slow_get: {
        parameters: {
            query?: {
                delay_ms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unreliable_endpoint_demo_unreliable_get: {
        parameters: {
            query?: {
                fail_rate?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreliableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_counter_demo_counter_get: {
        parameters: {
            query?: {
                counter_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    increment_counter_demo_counter_increment_post: {
        parameters: {
            query?: {
                counter_id?: string;
                amount?: number;
                should_fail?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_counter_demo_counter_reset_post: {
        parameters: {
            query?: {
                counter_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_notification_demo_notify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paginated_items_demo_items_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                delay_ms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_detail_demo_items__item_id__get: {
        parameters: {
            query?: {
                delay_ms?: number;
            };
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_time_demo_time_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerTimeResponse"];
                };
            };
        };
    };
    get_weather_demo_weather_get: {
        parameters: {
            query?: {
                city?: string;
                delay_ms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_demo_stock_get: {
        parameters: {
            query?: {
                symbol?: string;
                delay_ms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_demo_news_get: {
        parameters: {
            query?: {
                delay_ms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_error_demo_error__status_code__get: {
        parameters: {
            query?: {
                delay_ms?: number;
            };
            header?: never;
            path: {
                status_code: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rbac_me_demo_rbac_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RbacMeResponse"];
                };
            };
        };
    };
    set_demo_role_demo_rbac_set_role_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_protected_action_demo_rbac_protected_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtectedActionResponse"];
                };
            };
        };
    };
}
