"""add email auth fields

Revision ID: 93157a7be162
Revises: 747077f6ff17
Create Date: 2025-11-23 23:52:53.059149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93157a7be162'
down_revision: Union[str, None] = '747077f6ff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'group_invites', ['code'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True))

    # Create partial unique index for verified emails (case-insensitive)
    op.execute("""
        CREATE UNIQUE INDEX ix_users_email_verified
        ON users(LOWER(email))
        WHERE email_verified = true
    """)

    # Create regular index for email lookups (case-insensitive)
    op.execute("""
        CREATE INDEX ix_users_email
        ON users(LOWER(email))
        WHERE email IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_email_verified', table_name='users')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'group_invites', type_='unique')
    # ### end Alembic commands ###
