"""add_user_role

Revision ID: caf4f8eaf8d7
Revises: f564dec7eeff
Create Date: 2025-12-04 14:16:42.546391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf4f8eaf8d7'
down_revision: Union[str, None] = 'f564dec7eeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(20), nullable=False, server_default='user'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_friendships_user_id1'), 'friendships', ['user_id1'], unique=False)
    op.create_index(op.f('ix_friendships_user_id2'), 'friendships', ['user_id2'], unique=False)
    op.create_unique_constraint('uq_friendship', 'friendships', ['user_id1', 'user_id2'])
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_constraint('uq_friendship', 'friendships', type_='unique')
    op.drop_index(op.f('ix_friendships_user_id2'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_id1'), table_name='friendships')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
